### ISSUE TITLE
Port contracts to truffle or something similar

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/miximus#4]

**Comment by ldct** [comment]
I'd actually suggest using a testing backend like pyethereum or py-evm, would be a lighter-weight way to test the contracts.

**Comment by barryWhiteHat** [comment]
I am happy with that. 

The advantage of the truffle/embark. Is that it its js based which means that the testing stuff can be reused in places to make a web application. But given that we are doing zksnarks with a 800gb proving key this is probably not going to play nice in browser. Mostly my suggestion of truffle is thats what most people use. I get really frustrated with truffle. 

@nvonpentz offered to write some tests/ui iirc. Could you weigh in?

**Comment by nvonpentz** [comment]
@barrywhitehat I don't think that was me, but I'm definitely interested in writing tests as well as helping with other issues.

That said, I also get frustrated with truffle and would not be opposed if you used pyethereum.

> 800gb proving key

I really hope you mean mb.

**Comment by barryWhiteHat** [comment]
I do mean MB ;-)

Cool. Another advantage of pyethereum is it will be easy to call cpp functions which means the testing can be done to test the contracts and the zksnark circuit. 

So cool. I think we are agreed :D lets go with python.

**Comment by eolszewski** [comment]
@barryWhiteHat would there be any problem storing that in a chrome extension?

**Comment by barryWhiteHat** [comment]
I am unsure, The proving key right now is 400MB compressed. I think you should be able to do it. But i want to check with the zcash ppl how they do it. 

I am closing this issue but lets keep discussing here or on (gitter)[https://gitter.im/barrywhitehat/miximus_eth]
